### ISSUE TITLE
Supporting  jinja2>=3.0.3

### ISSUE THREAD

**Issue by GaoGN** [theislab/ncem#132]
**I have a problem with installing ncem in my virtual environment.**

My environment is pre-installed with jupyterlab-server 2.11.2 requiring jinja2>=3.0.3. When I tried to install ncem, I received an error message stating that it requires jinja2<3.0.0,>=2.11.3.  

**Could you please update ncem to support Jinja2>=3.0.3? **

**Comment by AnnaChristina** [comment]
resolved in ncem version 1.5.0
