### ISSUE TITLE
cannot get the grid search results

### ISSUE THREAD

**Issue by cam1flag** [theislab/ncem#151]
Hi,

I ran this block from the tutorial_mibitof notebook

`gs = ncem.train.GridSearchContainer(
    '/home/mohammed/NCEM/Anna Schaar/grid_searches_gen/', 
    gs_ids=[
        "210419_INTERACTIONS_BASELINE_NONE_NODES_IMAGE_1_HARTMANN",
        "210419_INTERACTIONS_MAX_NODES_IMAGE_1_HARTMANN",
    ],
    lateral_resolution = 400/1024
)
gs.load_gs()

gs.plot_best_model_by_hyperparam(
    graph_model_class='interactions',
    baseline_model_class='interactions_baseline',
    rename_levels = [
        ("model", {
            "INTERACTIONS_BASELINE_NONE_NODES_IMAGE_1": "baseline",
            "INTERACTIONS_MAX_NODES_IMAGE_1": "NCEM",
        })
    ],
    xticks=[0, 10, 50, 200, 1000],
)
`

and got this error

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[12], line 9
      1 gs = ncem.train.GridSearchContainer(
      2     '/home/mohammed/NCEM/Anna Schaar/grid_searches_gen/', 
      3     gs_ids=[
   (...)
      7     lateral_resolution = 400/1024
      8 )
----> 9 gs.load_gs()
     11 gs.plot_best_model_by_hyperparam(
     12     graph_model_class='interactions',
     13     baseline_model_class='interactions_baseline',
   (...)
     20     xticks=[0, 10, 50, 200, 1000],
     21 )

File ~/.local/lib/python3.8/site-packages/ncem/train/summaries.py:114, in GridSearchContainer.load_gs(self, expected_pickle, add_posterior_sampling_model, report_unsuccessful_runs)
    106 indir = self.source_path + gs_id + "/results/"
    107 # runs_ids are the unique hyper-parameter settings, which are again subsetted by cross-validation.
    108 # These ids are present in all files names but are only collected from the *model.tf file names here.
    110 run_ids = np.sort(
    111     np.unique(
    112         [
    113             "_".join(".".join(x.split(".")[:-1]).split("_")[:-1])
--> 114             for x in os.listdir(indir)
    115             if x.split("_")[-1].split(".")[0] == "time"
    116         ]
    117     )
    118 )
    119 cv_ids = np.sort(np.unique([x.split("_")[-1] for x in run_ids]))  # identifiers of cross-validation splits
    120 run_ids = np.sort(
    121     np.unique(["_".join(x.split("_")[:-1]) for x in run_ids])  # identifiers of hyper-parameters settings
    122 )

FileNotFoundError: [Errno 2] No such file or directory: '/home/med/NCEM/Anna Schaar/grid_searches_gen/210419_INTERACTIONS_BASELINE_NONE_NODES_IMAGE_1_HARTMANN/results/'

Could you help?
Thanks

**Comment by AnnaChristina** [comment]
Hi @cam1flag, thanks for your interest in using ncem. 

We do not provide the entire grid search results but provide script how to obtain them here: https://github.com/theislab/ncem_benchmarks/tree/main/scripts

hope this helps!
