### ISSUE TITLE
How to implement Input CODEX data for 'NCEM

### ISSUE THREAD

**Issue by Luosanj** [theislab/ncem#93]
I am appreciated by your excellent work. I plan to use 'NCEM' package with my CODEX image data. Yet, I failed to load my data referring the tutorial code. I find there are a lot of prefix like 'zhang','Hartmann' to build a dataloader. I don't know how to choose them. May I request for a help?

**Comment by AnnaChristina** [comment]
Hi @Luosanj ,

links to: https://github.com/theislab/ncem_tutorials/issues/1#issuecomment-1165669767

answering here to keep it better traceable with respect to issues. 

May I ask which ncem version you have installed. We only added the cutsom data loader recently, so you might need to update ncem to use it. 

Additionally the Codex data we are using in the manuscrip is taken from this manuscript:

CODEX - cancer
Schürch, C. M. et al. Coordinated Cellular Neighborhoods Orchestrate Antitumoral Immunity at the Colorectal Cancer Invasive Front. Cell 183, 838 (2020).

Data can be downloaded from https://data.mendeley.com/datasets/mpjzbtfgfr/1 To run NCEM download the CRC_clusters_neighborhoods_markers.csv and store it to a data directory of your choice.

**Comment by Luosanj** [comment]
Hi @AnnaChristina ,
     Thanks for your response !  I have uninstall and  reinstall the package 'ncem', but the version didn't change which is 0.1.0. What is the right version supposed to be? 
![image](https://user-images.githubusercontent.com/46926952/175611139-710fc7db-4f63-4dfd-a592-95bef7059acb.png)

Cheers,

**Comment by Luosanj** [comment]
I find that in your tutorial the right version for ncem is 0.1.3. Yet I cannot find this version using command 'pip install'. 
![image](https://user-images.githubusercontent.com/46926952/175752811-245b313b-5908-4d65-807f-3a47162c3397.png)

**Comment by Luosanj** [comment]
Thanks for answering Anna ! By the way may I ask is there a tutorial on how to run the 'Encoder Decoder with one layer GCN embedding' model mentioned in your paper ? Currently it seems only linear model can be run. Thanks !

**Comment by Luosanj** [comment]
@AnnaChristina

**Comment by AnnaChristina** [comment]
you can also use the non-linear ncem models by switching the model type to `ed_ncem` or `cvae_ncem` and the respective gnn layer specified. For simplicity, we currently do not provide a tutorial for all the different model set-ups but it follows the same logic and https://github.com/theislab/ncem_benchmarks/tree/main/scripts shows further examples how the different models can be run and hyperparameter suggestions for the different pre-selected datasets.

**Comment by AnnaChristina** [comment]
closing the issue due to inactivity. Please feel free to open the issue again, in case of further questions!
